name: flexi_toast
description: "A new Flutter project."
homepage: https://github.com/badiniibrahim/flutter_flexi_toast
repository: https://github.com/badiniibrahim/flutter_flexi_toast

version: 1.0.0

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
